name: jsr

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.0.0-rc.4
      - name: Publish
        run: |
          deno run --allow-all jsr:@david/publish-on-tag@0.1.4
